# Generated by Django 4.2 on 2023-05-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=120, verbose_name='User Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Phone_Num', models.CharField(max_length=40, verbose_name='Phone Number')),
                ('Birth_Date', models.DateTimeField(verbose_name='BirthDate')),
                ('Gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('AddressL1', models.CharField(max_length=120, verbose_name='Address Line 1')),
                ('AddressL2', models.CharField(max_length=120, verbose_name='Address Line 2')),
                ('Country', models.CharField(max_length=120, verbose_name='Country')),
                ('City', models.CharField(max_length=120, verbose_name='City')),
                ('Region', models.CharField(max_length=120, verbose_name='Region')),
                ('Postal_Code', models.CharField(max_length=20, verbose_name='Postal Code')),
            ],
        ),
    ]
