# Generated by Django 4.2 on 2023-12-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BusRoute',
        ),
    ]
