# Generated by Django 4.2 on 2023-12-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_busticket_delete_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('total_fee', models.FloatField(blank=True, null=True)),
                ('bus_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BusTicket',
        ),
    ]
