# Generated by Django 4.2 on 2023-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_busticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('initial_fare', models.FloatField(blank=True, null=True)),
                ('discount', models.CharField(choices=[('student', 'Student (20% discount)'), ('senior_citizen', 'Senior Citizen'), ('voucher', 'Voucher'), ('none', 'None')], default='none', max_length=15)),
                ('total_fare', models.FloatField(blank=True, null=True)),
                ('bus_type', models.CharField(max_length=100)),
                ('payment_method', models.CharField(default='gcash', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BusTicket',
        ),
    ]
